const novaModel = 'nova-3';
const whisperModel = 'whisper';

export const nova3LanguageCodes = new Set([
  'ar',
  'be',
  'bn',
  'bs',
  'bg',
  'ca',
  'zh',
  'hr',
  'cs',
  'da',
  'nl',
  'en',
  'et',
  'fi',
  'fr',
  'de',
  'el',
  'gu',
  'he',
  'hi',
  'hu',
  'id',
  'it',
  'ja',
  'kn',
  'ko',
  'lv',
  'lt',
  'mk',
  'ms',
  'mr',
  'no',
  'fa',
  'pl',
  'pt',
  'ro',
  'ru',
  'sr',
  'sk',
  'sl',
  'es',
  'sv',
  'tl',
  'ta',
  'te',
  'th',
  'tr',
  'uk',
  'ur',
  'vi',
]);

export const languages = [
  { label: 'Auto Detect', code: null, deepgramCode: null, deepgramModel: whisperModel, detectLanguage: true },
  { label: 'Afrikaans', code: 'af', deepgramCode: 'af', deepgramModel: whisperModel },
  { label: 'Albanian', code: 'sq', deepgramCode: 'sq', deepgramModel: whisperModel },
  { label: 'Amharic', code: 'am', deepgramCode: 'am', deepgramModel: whisperModel },
  { label: 'Arabic', code: 'ar', deepgramCode: 'ar', deepgramModel: whisperModel },
  { label: 'Armenian', code: 'hy', deepgramCode: 'hy', deepgramModel: whisperModel },
  { label: 'Assamese', code: 'as', deepgramCode: 'as', deepgramModel: whisperModel },
  { label: 'Azerbaijani', code: 'az', deepgramCode: 'az', deepgramModel: whisperModel },
  { label: 'Bashkir', code: 'ba', deepgramCode: 'ba', deepgramModel: whisperModel },
  { label: 'Basque', code: 'eu', deepgramCode: 'eu', deepgramModel: whisperModel },
  { label: 'Belarusian', code: 'be', deepgramCode: 'be', deepgramModel: whisperModel },
  { label: 'Bengali', code: 'bn', deepgramCode: 'bn', deepgramModel: whisperModel },
  { label: 'Bosnian', code: 'bs', deepgramCode: 'bs', deepgramModel: whisperModel },
  { label: 'Breton', code: 'br', deepgramCode: 'br', deepgramModel: whisperModel },
  { label: 'Bulgarian', code: 'bg', deepgramCode: 'bg', deepgramModel: whisperModel },
  { label: 'Burmese', code: 'my', deepgramCode: 'my', deepgramModel: whisperModel },
  { label: 'Catalan', code: 'ca', deepgramCode: 'ca', deepgramModel: whisperModel },
  { label: 'Chinese', code: 'zh', deepgramCode: 'zh', deepgramModel: whisperModel },
  { label: 'Croatian', code: 'hr', deepgramCode: 'hr', deepgramModel: whisperModel },
  { label: 'Czech', code: 'cs', deepgramCode: 'cs', deepgramModel: whisperModel },
  { label: 'Danish', code: 'da', deepgramCode: 'da', deepgramModel: whisperModel },
  { label: 'Dutch', code: 'nl', deepgramCode: 'nl', deepgramModel: whisperModel },
  { label: 'English', code: 'en', deepgramCode: 'en', deepgramModel: whisperModel },
  { label: 'Estonian', code: 'et', deepgramCode: 'et', deepgramModel: whisperModel },
  { label: 'Faroese', code: 'fo', deepgramCode: 'fo', deepgramModel: whisperModel },
  { label: 'Finnish', code: 'fi', deepgramCode: 'fi', deepgramModel: whisperModel },
  { label: 'French', code: 'fr', deepgramCode: 'fr', deepgramModel: whisperModel },
  { label: 'Galician', code: 'gl', deepgramCode: 'gl', deepgramModel: whisperModel },
  { label: 'Georgian', code: 'ka', deepgramCode: 'ka', deepgramModel: whisperModel },
  { label: 'German', code: 'de', deepgramCode: 'de', deepgramModel: whisperModel },
  { label: 'Greek', code: 'el', deepgramCode: 'el', deepgramModel: whisperModel },
  { label: 'Gujarati', code: 'gu', deepgramCode: 'gu', deepgramModel: whisperModel },
  { label: 'Haitian Creole', code: 'ht', deepgramCode: 'ht', deepgramModel: whisperModel },
  { label: 'Hausa', code: 'ha', deepgramCode: 'ha', deepgramModel: whisperModel },
  { label: 'Hawaiian', code: 'haw', deepgramCode: 'haw', deepgramModel: whisperModel },
  { label: 'Hebrew', code: 'he', deepgramCode: 'he', deepgramModel: whisperModel },
  { label: 'Hindi', code: 'hi', deepgramCode: 'hi', deepgramModel: whisperModel },
  { label: 'Hungarian', code: 'hu', deepgramCode: 'hu', deepgramModel: whisperModel },
  { label: 'Icelandic', code: 'is', deepgramCode: 'is', deepgramModel: whisperModel },
  { label: 'Indonesian', code: 'id', deepgramCode: 'id', deepgramModel: whisperModel },
  { label: 'Italian', code: 'it', deepgramCode: 'it', deepgramModel: whisperModel },
  { label: 'Japanese', code: 'ja', deepgramCode: 'ja', deepgramModel: whisperModel },
  { label: 'Javanese', code: 'jw', deepgramCode: 'jw', deepgramModel: whisperModel },
  { label: 'Kannada', code: 'kn', deepgramCode: 'kn', deepgramModel: whisperModel },
  { label: 'Kazakh', code: 'kk', deepgramCode: 'kk', deepgramModel: whisperModel },
  { label: 'Khmer', code: 'km', deepgramCode: 'km', deepgramModel: whisperModel },
  { label: 'Korean', code: 'ko', deepgramCode: 'ko', deepgramModel: whisperModel },
  { label: 'Lao', code: 'lo', deepgramCode: 'lo', deepgramModel: whisperModel },
  { label: 'Latin', code: 'la', deepgramCode: 'la', deepgramModel: whisperModel },
  { label: 'Latvian', code: 'lv', deepgramCode: 'lv', deepgramModel: whisperModel },
  { label: 'Lingala', code: 'ln', deepgramCode: 'ln', deepgramModel: whisperModel },
  { label: 'Lithuanian', code: 'lt', deepgramCode: 'lt', deepgramModel: whisperModel },
  { label: 'Luxembourgish', code: 'lb', deepgramCode: 'lb', deepgramModel: whisperModel },
  { label: 'Macedonian', code: 'mk', deepgramCode: 'mk', deepgramModel: whisperModel },
  { label: 'Malagasy', code: 'mg', deepgramCode: 'mg', deepgramModel: whisperModel },
  { label: 'Malay', code: 'ms', deepgramCode: 'ms', deepgramModel: whisperModel },
  { label: 'Malayalam', code: 'ml', deepgramCode: 'ml', deepgramModel: whisperModel },
  { label: 'Maltese', code: 'mt', deepgramCode: 'mt', deepgramModel: whisperModel },
  { label: 'Maori', code: 'mi', deepgramCode: 'mi', deepgramModel: whisperModel },
  { label: 'Marathi', code: 'mr', deepgramCode: 'mr', deepgramModel: whisperModel },
  { label: 'Mongolian', code: 'mn', deepgramCode: 'mn', deepgramModel: whisperModel },
  { label: 'Nepali', code: 'ne', deepgramCode: 'ne', deepgramModel: whisperModel },
  { label: 'Norwegian', code: 'no', deepgramCode: 'no', deepgramModel: whisperModel },
  { label: 'Norwegian Nynorsk', code: 'nn', deepgramCode: 'nn', deepgramModel: whisperModel },
  { label: 'Occitan', code: 'oc', deepgramCode: 'oc', deepgramModel: whisperModel },
  { label: 'Pashto', code: 'ps', deepgramCode: 'ps', deepgramModel: whisperModel },
  { label: 'Persian', code: 'fa', deepgramCode: 'fa', deepgramModel: whisperModel },
  { label: 'Polish', code: 'pl', deepgramCode: 'pl', deepgramModel: whisperModel },
  { label: 'Portuguese', code: 'pt', deepgramCode: 'pt', deepgramModel: whisperModel },
  {
    label: 'Punjabi (Shahmukhi)',
    code: 'pa',
    deepgramCode: 'pa',
    deepgramModel: whisperModel,
    outputScript: 'shahmukhi',
    correctionLanguage: 'Punjabi in Shahmukhi script',
  },
  {
    label: 'Punjabi (Gurmukhi)',
    code: 'pa',
    deepgramCode: 'pa',
    deepgramModel: whisperModel,
    outputScript: 'gurmukhi',
    correctionLanguage: 'Punjabi in Gurmukhi script',
  },
  { label: 'Romanian', code: 'ro', deepgramCode: 'ro', deepgramModel: whisperModel },
  { label: 'Russian', code: 'ru', deepgramCode: 'ru', deepgramModel: whisperModel },
  { label: 'Sanskrit', code: 'sa', deepgramCode: 'sa', deepgramModel: whisperModel },
  { label: 'Serbian', code: 'sr', deepgramCode: 'sr', deepgramModel: whisperModel },
  { label: 'Shona', code: 'sn', deepgramCode: 'sn', deepgramModel: whisperModel },
  { label: 'Sindhi', code: 'sd', deepgramCode: 'sd', deepgramModel: whisperModel },
  { label: 'Sinhala', code: 'si', deepgramCode: 'si', deepgramModel: whisperModel },
  { label: 'Slovak', code: 'sk', deepgramCode: 'sk', deepgramModel: whisperModel },
  { label: 'Slovenian', code: 'sl', deepgramCode: 'sl', deepgramModel: whisperModel },
  { label: 'Somali', code: 'so', deepgramCode: 'so', deepgramModel: whisperModel },
  { label: 'Spanish', code: 'es', deepgramCode: 'es', deepgramModel: whisperModel },
  { label: 'Sundanese', code: 'su', deepgramCode: 'su', deepgramModel: whisperModel },
  { label: 'Swahili', code: 'sw', deepgramCode: 'sw', deepgramModel: whisperModel },
  { label: 'Swedish', code: 'sv', deepgramCode: 'sv', deepgramModel: whisperModel },
  { label: 'Tagalog', code: 'tl', deepgramCode: 'tl', deepgramModel: whisperModel },
  { label: 'Tajik', code: 'tg', deepgramCode: 'tg', deepgramModel: whisperModel },
  { label: 'Tamil', code: 'ta', deepgramCode: 'ta', deepgramModel: whisperModel },
  { label: 'Tatar', code: 'tt', deepgramCode: 'tt', deepgramModel: whisperModel },
  { label: 'Telugu', code: 'te', deepgramCode: 'te', deepgramModel: whisperModel },
  { label: 'Thai', code: 'th', deepgramCode: 'th', deepgramModel: whisperModel },
  { label: 'Tibetan', code: 'bo', deepgramCode: 'bo', deepgramModel: whisperModel },
  { label: 'Turkish', code: 'tr', deepgramCode: 'tr', deepgramModel: whisperModel },
  { label: 'Turkmen', code: 'tk', deepgramCode: 'tk', deepgramModel: whisperModel },
  { label: 'Ukrainian', code: 'uk', deepgramCode: 'uk', deepgramModel: whisperModel },
  { label: 'Urdu', code: 'ur', deepgramCode: 'ur', deepgramModel: whisperModel },
  { label: 'Uzbek', code: 'uz', deepgramCode: 'uz', deepgramModel: whisperModel },
  { label: 'Vietnamese', code: 'vi', deepgramCode: 'vi', deepgramModel: whisperModel },
  { label: 'Welsh', code: 'cy', deepgramCode: 'cy', deepgramModel: whisperModel },
  { label: 'Yiddish', code: 'yi', deepgramCode: 'yi', deepgramModel: whisperModel },
  { label: 'Yoruba', code: 'yo', deepgramCode: 'yo', deepgramModel: whisperModel },
].map((language) => ({
  ...language,
  deepgramModel: nova3LanguageCodes.has(language.code)
    ? novaModel
    : language.deepgramModel,
}));

const aliases = new Map([
  ['auto', 'Auto Detect'],
  ['auto detect', 'Auto Detect'],
  ['automatic', 'Auto Detect'],
  ['francais', 'French'],
  ['français', 'French'],
  ['deutsch', 'German'],
  ['indonesia', 'Indonesian'],
  ['bahasa indonesia', 'Indonesian'],
  ['italiano', 'Italian'],
  ['korian', 'Korean'],
  ['korean', 'Korean'],
  ['bahasa melayu', 'Malay'],
  ['bahasa malaysia', 'Malay'],
  ['portugues', 'Portuguese'],
  ['português', 'Portuguese'],
  ['punjabi', 'Punjabi (Shahmukhi)'],
  ['punjabi shahmukhi', 'Punjabi (Shahmukhi)'],
  ['punjabi (shahmukhi)', 'Punjabi (Shahmukhi)'],
  ['shahmukhi punjabi', 'Punjabi (Shahmukhi)'],
  ['punjabi gurmukhi', 'Punjabi (Gurmukhi)'],
  ['punjabi (gurmukhi)', 'Punjabi (Gurmukhi)'],
  ['gurmukhi punjabi', 'Punjabi (Gurmukhi)'],
  ['pyccknn (russian)', 'Russian'],
  ['русский', 'Russian'],
  ['russian', 'Russian'],
  ['espanol', 'Spanish'],
  ['espanol (spanish)', 'Spanish'],
  ['español', 'Spanish'],
  ['spanish', 'Spanish'],
  ['turkce', 'Turkish'],
  ['tukce', 'Turkish'],
  ['türkçe', 'Turkish'],
  ['turkish', 'Turkish'],
]);

export function resolveLanguage(languageLabel = 'Auto Detect') {
  const rawLabel = String(languageLabel || 'Auto Detect').trim();
  const normalized = rawLabel.toLowerCase();
  const aliasedLabel = aliases.get(normalized) || rawLabel;
  const language = languages.find((item) => item.label.toLowerCase() === aliasedLabel.toLowerCase());

  if (!language) {
    return null;
  }

  return language;
}
